export const services = [
  {
    id: 1,
    name1: "SEO",
    name2: "оптимизация",
    background: "bg-zinc-100",
    arrow: "/services/ag.svg",
    link: "./",
    image: "/services/01.svg",
  },
  {
    id: 2,
    name1: "Настройка",
    name2: "рекламы",
    background: "bg-lime",
    arrow: "/services/ag.svg",
    link: "./",
    image: "/services/02.svg",
  },
  {
    id: 3,
    name1: "Продвижение",
    name2: "в соц сетях",
    background: "bg-black",
    arrow: "/services/aw.svg",
    link: "./",
    image: "/services/03.svg",
  },
  {
    id: 4,
    name1: "Email",
    name2: "маркетинг",
    background: "bg-zinc-100",
    arrow: "/services/ag.svg",
    link: "./",
    image: "/services/04.svg",
  },
  {
    id: 5,
    name1: "Создание",
    name2: "контента",
    background: "bg-lime",
    arrow: "/services/ag.svg",
    link: "./",
    image: "/services/05.svg",
  },
  {
    id: 6,
    name1: "Аналитика и",
    name2: "трекинг",
    background: "bg-black",
    arrow: "/services/aw.svg",
    link: "./",
    image: "/services/06.svg",
  },
];
